export const data = [
  {
    id: 1,
    foodName: "Artichokes",
    price: 3625,
    img: "./first.png",
    categoryName: "Temp Fencing, Decorative Fencing and Gates",
  },
  {
    id: 2,
    foodName: "Pastry",
    price: 5249,
    img: "./second.png",
    categoryName: "Plumbing & Medical Gas",
  },
  {
    id: 3,
    foodName: "Olives",
    price: 5979,
    img: "./third.png",
    categoryName: "Asphalt Paving",
  },
  {
    id: 4,
    foodName: "Bread",
    price: 3126,
    img: "./forth.png",
    categoryName: "Soft Flooring and Base",
  },
  {
    id: 5,
    foodName: "Juice",
    price: 3920,
    img: "./fifth.png",
    categoryName: "Exterior Signage",
  },
  {
    id: 6,
    foodName: "Parsnip",
    price: 8351,
    img: "./sixth.png",
    categoryName: "Wall Protection",
  },
  {
    id: 7,
    foodName: "Onion Powder",
    price: 7974,
    img: "./seventh.png",
    categoryName: "Roofing (Asphalt)",
  },
  {
    id: 8,
    foodName: "Goat",
    price: 6446,
    img: "./eighth.png",
    categoryName: "Drywall & Acoustical (MOB)",
  },
  {
    id: 9,
    foodName: "Soup",
    price: 9383,
    img: "./nine.png",
    categoryName: "Marlite Panels (FED)",
  },
  {
    id: 10,
    foodName: "Wine",
    price: 6330,
    img: "./ten.png",
    categoryName: "Painting & Vinyl Wall Covering",
  },
  {
    id: 11,
    foodName: "Wine",
    price: 4411,
    img: "./eleven.png",
    categoryName: "Electrical and Fire Alarm",
  },
  {
    id: 12,
    foodName: "Muffin",
    price: 9563,
    img: "./twelve.png",
    categoryName: "Sitework & Site Utilities",
  },
  {
    id: 13,
    foodName: "Ice Wine",
    price: 9452,
    img: "./thirteen.png",
    categoryName: "Soft Flooring and Base",
  },
  {
    id: 14,
    foodName: "Delicato Merlot",
    price: 7529,
    img: "./fortheen.png",
    categoryName: "HVAC",
  },
  {
    id: 15,
    foodName: "Chateau Bonnet",
    price: 4157,
    img: "./fifteen.png",
    categoryName: "Framing (Steel)",
  },
  {
    id: 16,
    foodName: "Cinnamon",
    price: 5851,
    img: "./sixteen.png",
    categoryName: "Asphalt Paving",
  },
];
